# Generated by Django 3.2.16 on 2023-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_city_contact_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('decs', models.TextField()),
                ('img', models.ImageField(upload_to='teacher')),
            ],
        ),
    ]
